# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88f6d53fbca68740bc1a9104e300f55e9b7e1747851442e5de4d16e50b37e64291d07d79a07f4eb2c970f9aac6c41e5d31973f03658e459666c7d27205d05624

test:
  secret_key_base: c5f5b99636e46e622b2b46f30be3ae586f9c82ec380071681c5b52273659b172e4c15d6efa05d5f41bf15d50a3efc7d3a70a29a6a7063151d694b257bc59251a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
